### ISSUE TITLE
[Feature request] Customize Readable Line Length

### ISSUE THREAD

**Issue by bwoah-md** [Erallie/colored-candy#2]
it'd be great if we could get a style settings option to add readable line length ourselves

re: https://discord.com/channels/686053708261228577/1277415156099448855/1278419059721109567

couldn't post the video here because it's too large in size, sorry :(

**Comment by Erallie** [comment]
That's okay! I will work on getting integrating with Style Settings today!

**Comment by Erallie** [comment]
I have implemented settings to adjust the readable line length! It just needs testing!

**Comment by ElsaTam** [comment]
Works like a charm!
Just one remark, in the Style settings, the description "_Readable line length can be enabled under Settings -> Editor -> Readable line length_" is shown a as a new setting item. Maybe get it up with the first part of the description "_The maximum length when "Readble line length" is enable._"?

**Comment by Erallie** [comment]
> Maybe get it up with the first part of the description "_The maximum length when "Readble line length" is enable._"?

@ElsaTam The reason why I decided to make it a new setting item is because I can't use markdown to make **Settings → Editor → Readable line length** bold unless it's its own setting.

**Comment by ElsaTam** [comment]
@Erallie Oh well, that is unfortunate :( Thanks for the explanation!

**Comment by Erallie** [comment]
I'm gonna close this issue now, seeing that everyone is happy with it ^^
