### ISSUE TITLE
[Feature request] Tooltips Styling

### ISSUE THREAD

**Issue by bwoah-md** [Erallie/colored-candy#3]
![image](https://github.com/user-attachments/assets/08a817b0-f4ec-4742-a90f-b8b29e3ec230)

add the theme styling to tooltips as well

**Comment by Erallie** [comment]
I will play around with the tooltips and see what I can do!

**Comment by Erallie** [comment]
@bwoah-md I added styles for tooltips! It would be great if you could test it out for me!

**Comment by Erallie** [comment]
@ElsaTam Can you test this out too?

**Comment by ElsaTam** [comment]
@Erallie  It is now Kapirklaa approved!

**Comment by Erallie** [comment]
Perfect! I will close this issue now.

**Comment by bwoah-md** [comment]
> @bwoah-md I added styles for tooltips! It would be great if you could test it out for me!

yes it works perfectly well now, thanks erallie and sorry for the late reply 😅

_its icy approved as well 😉_

**Comment by Erallie** [comment]
@bwoah-md Wonderful! Thank you for getting back on this! 😄
